#!/bin/bash

set -euo pipefail

echo "Building contivvpp agent binary..."
dev_vswitch_ids="$(docker images contivvpp/dev-vswitch --format "{{.ID}}")"
dev_vswitch_id="$(echo $dev_vswitch_ids | awk '{print $1;}')"
docker kill dev-contiv || true
docker run -v /home/vagrant/gopath/src/github.com/americanbinary/vpp/:/root/go/src/github.com/americanbinary/vpp/ -itd --name dev-contiv --rm $dev_vswitch_id bash
docker exec -it dev-contiv bash -c "cd /root/go/src/github.com/americanbinary/vpp; make agent; make contiv-init"
docker kill dev-contiv

echo "Building and saving contivvpp/vswitch image..."
cd /home/vagrant/gopath/src/github.com/americanbinary/vpp/docker/development; ./build.sh
docker save contivvpp/vswitch:latest > /vagrant/config/vswitch.tar
